### ISSUE TITLE
插件重载不应该重新创建 tables

### ISSUE THREAD

**Issue by z0z0r4** [z0z0r4/better_backup#19]
![image](https://github.com/z0z0r4/better_backup/assets/78744121/3aacf7bb-8a93-4469-b0c1-1f3ed0328eca)

**Comment by z0z0r4** [comment]
我回来再慢慢修吧...现在马上返校 re0 了

**Comment by alex3236** [comment]
define_table 不应该在已存在 table 的情况下再次创建，这可能是上游问题

**Comment by z0z0r4** [comment]
eee，修了吗？如修

**Comment by alex3236** [comment]
reopen干嘛（
