### ISSUE TITLE
ZSTD 压缩备份文件

### ISSUE THREAD

**Issue by z0z0r4** [z0z0r4/better_backup#7]
效果显著，未来可期，下次一定
![image](https://github.com/z0z0r4/better_backup/assets/78744121/ee5ab2e8-470e-4c53-9eee-728f1056b702)

**Comment by alex3236** [comment]
似乎不难实现 复制改一下就好

**Comment by z0z0r4** [comment]
> 似乎不难实现 复制改一下就好

我要看番，现在没啥必要功能了，留着下辈子的工作

**Comment by alex3236** [comment]
> 我要看番，现在没啥必要功能了，留着下辈子的工作

你本地有什么大改动吗 我试试PR？

**Comment by z0z0r4** [comment]
有，马上push

**Comment by z0z0r4** [comment]
finished v1.1.0 https://github.com/z0z0r4/better_backup/pull/9
